
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar1 from "./component/navbar"
import Navbar2 from "./component/Navbar2"
import Navbar3 from "./component/navbar3"
import Footer from "./component/footer/footer"
import { CartProvider } from "./component/context/CartContext"





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
         {/* ✅ wrap everything */}
         <CartProvider>
          <header>
            <div>
              <Navbar1 />
              <Navbar2 />
              <div className="hidden sm:block">
                <Navbar3 />
              </div>
            </div>
          </header>

          <main>
            {children}
          </main>

          <footer>
            <Footer />
          </footer>
        </CartProvider>
      </body>
      
    </html>
  );
}